name = "defol"
description = "A command-line tool to find duplicated folders"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "GPL-3.0-only"
website = ""
tags = ["folder", "directory", "duplicates", "deduplication"]

executables = ["defol"]

[test]
runner = "alire"

[[depends-on]]
den = "~0.1.0"
gnat = "<15 | >=16" # Linking error maybe related to `for ... of` notation
parse_args = "~0.9.0"
simple_logging = "^1.2.0"
stopwatch = "~0.1.0"

[[pins]]
den_tests = { path = "../den/tests" }
simple_logging = { path = "../simple_logging" }
